### ISSUE TITLE
No full-screen function on companion app

### ISSUE THREAD

**Issue by srodighiero** [AlexxIT/WebRTC#300]
Did non have a chance to test it on android. Full-screen function working fine on web interface, button is missing on companion app, while sound and play/pause buttons are present and working

**Comment by cbroissa-github** [comment]
I have the same problem with IOS, with ui: true
There is no full screen button.
![0D926ECF-C39C-485C-B0A3-3AA6DB9E35B6](https://user-images.githubusercontent.com/83312047/169416852-77281a8a-d581-4e2c-9996-1ddaec33f426.jpeg)

**Comment by ammaralfarsi** [comment]
even unable to unmute. it gets muted again if i try to unmute it

**Comment by srodighiero** [comment]
@ammaralfarsi same for me. Workaround in my case is to hold the mute/unmute button for few seconds.

**Comment by ammaralfarsi** [comment]
> @ammaralfarsi same for me. Workaround in my case is to hold the mute/unmute button for few seconds.

Just tried it and it works when i hold if for few secs.

Thx

**Comment by andyp05** [comment]
Updated to HA 2022.7 and WebRTC 2.3.1. Cameras work fine with full-screen option on iPhone until I set ui: true
Mute on/off does not work even if I press for seconds.

**Comment by keeema** [comment]
For me fullscreen still not working.
Home Assistant 2022.12.6
WebRTC Camera 2.3.1

**Comment by AlexxIT** [comment]
Unfortunately, the iPhone has the worst browser in the world today.
It does not support a lot of modern web technologies. Including MSE and Full screen:
https://caniuse.com/mediasource
https://caniuse.com/fullscreen

PS. No problem on desktop Mac or iPad. Only iPhones...

**Comment by MStcz** [comment]
> Unfortunately, the iPhone has the worst browser in the world today. It does not support a lot of modern web technologies. Including MSE and Full screen: https://caniuse.com/mediasource https://caniuse.com/fullscreen
> 
> PS. No problem on desktop Mac or iPad. Only iPhones...

Hi, I have very same problem also on iPad. When "ui: true" all buttons are gone. I can see them just for short time before the video is loaded.

Home Assistant 2023.1.1
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0
WebRTC-3.0-beta.3
iPadOS 16.2
Home Assistant app on iOS 2022.10.1

**Comment by jorisrymenants** [comment]
Full screen not showing for me on ios iphone 13 pro, ios 16.1.2
controls never show, not when UI: true is set, and not when it is not set
webrtc version: v3.0-beta4

ued to work in non v3 versions

**Comment by AlexxIT** [comment]
The iPhone browser does not support this feature

**Comment by jason0x43** [comment]
> The iPhone browser does not support this feature

WebRTC cards in iPhone Safari do show the normal video controls (play, stop, Airplay, full screen), and native Home Assistant video streams in the iPhone companion app also have the video controls, so videos _can_ show the controls. I don't know off the top of my head what the requirements are for doing so, though.

**Comment by AlexxIT** [comment]
@jason0x43 problem with custom UI. When native controls disabled

**Comment by jason0x43** [comment]
Odd that the issue only seems to apply to the iPhone companion app, and not the iPad companion app or Safari on any device.

Interestingly, with WebRTC v3.0.0 I get the custom UI (the PTZ controls, at least) and the native controls in the iPhone companion app, and all of them work.

**Comment by AlexxIT** [comment]
@MStcz custom UI should be fixed in latest release

**Comment by MStcz** [comment]
> @MStcz custom UI for iPad should be fixed in latest release

Hi @AlexxIT, thank you for the update. I can see custom shortcuts, speaker button at the bottom right but not full screen button at the bottom left. Tested on iPad with "ui: true".

Home Assistant  2023.1.7
Supervisor 2023.01.1
Operating System 9.4
Frontend Frontend 20230110.0
WebRTC v3.0.1
iPadOS 16.2
Home Assistant app on iOS 2022.10.1

**Comment by haforme** [comment]
I saw that this issue is closed but wanted to advise that the Full Screen Button is missing from iPAD IOS 16.2.  Iam running WebRTC version 3.0.2.  The Full Screen button appears and works on a PC web browser.

Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230201.0 - latest

**Comment by jason0x43** [comment]
Just for comparison, I'm also running HA 2023.2.0 and WebRTC 3.0.2, and the full screen button does show up on my iPad running iOS 16.2.

**Comment by haforme** [comment]
I cleared the cache in the companion app and that did not fix the issues.

Do you have "ui: true" in your webRTC card.  I do and the full screen indicator [ ] shows up in the bottom left corner of my PC but nothing for the app. Maybe that is the difference.   If I set "ui: false" then I see the arrows that allow me to stretch  the screen to full but then other items appear that I do not wish to see.

**Comment by jason0x43** [comment]
I have `ui: true`, and if I tap the video I see both the native controls and the WebRTC UI (the PTZ controls, at least).

![IMG_B414E2239363-1](https://user-images.githubusercontent.com/1042866/216490709-699960ca-719f-4d0f-b423-f3f0b140c63a.jpeg)

**Comment by MStcz** [comment]
> I have `ui: true`, and if I tap the video I see both the native controls and the WebRTC UI (the PTZ controls, at least).
> 

It is strange. I am able to achieve very same result as you but just with `ui: false`. In that case each time I open the stream can see  pause icon in the middle of the screen and partial opacity over the whole screen - I don 't like it. That 's why I prefer `ui: true` but there is no full screen mode button/icon.

iPad `ui: false` after click:
![iPad_3d_uif1](https://user-images.githubusercontent.com/44493334/216850093-2628405a-22cc-4ae1-8573-49bcb73ecbb5.JPEG)
_Zive Vysilani = Live Broadcast_

iPad `ui: false`:
![iPad_3d_uif2](https://user-images.githubusercontent.com/44493334/216850105-8fb52529-2273-4184-8dc8-4b014985ccb6.JPEG)

iPad `ui: true`:
![iPad_3d_uit](https://user-images.githubusercontent.com/44493334/216850108-70d6aaa3-4ea0-4922-aa4e-b02223afb233.JPEG)

Laptop `ui: true`:
![LT_3d_uit](https://user-images.githubusercontent.com/44493334/216850111-bf2339a9-47cc-4ddf-ae42-ec8ea3488137.jpg)

Laptop `ui: false`:
![LT_3d_uif](https://user-images.githubusercontent.com/44493334/216850113-7d0cd090-55a1-41e8-8c58-ea63021e437a.jpg)

**Comment by giantorth** [comment]
Would it be possible to have an option of "ui: supported" and not set custom UI for iOS browsers?
