### ISSUE TITLE
Fixing bug(s) on Javascript WebRTC Component / make it reliable

### ISSUE THREAD

**Issue by DzzD** [AlexxIT/WebRTC#367]
I have used WebRTC since a week now and think it great, but...

I have loads of problems which seem to come from the Javascript component, I believe it come from the JS part as refreshing browser usually correct the problem (and also for other reasons, exception in console log, etc...).

It would be hard to make an exhaustive list, but to make the story short when the player is running on desktop computer browser any change of DOM or event like blur/focus can cause it to crash and the component is unable to re-connect, this require to refresh several time the browser page to get the stream back.

I would like to help debug this part, what is the most convenient way to live test modifications ? I tried to change js file in the custom_component folder but it seems that it is not reloaded even when refreshing the browser, I suppose it is copy/cached once when HA start ?

**Comment by DzzD** [comment]
Using `background: true` resolve some DOM modifications problems, not all but at least it resolve resizing window problem when card are rearanged, so it may be nice when background is set to false to keep the stream "open" a cupple of second just to see if it is not required, or add a parameter `backgroundTimout: 5000` with default to 5/10 secondes, I would also help when changing from one screen to another with the same camera.

**Comment by AlexxIT** [comment]
This problems already fixed in go2rtc project. The changes will get into this project along with replacing rtsp2webrtc with go2rtc.

You also created a Discussion in the go2rtc project, but you attached screenshots of rtsp2webrtc. This is wrong.

**Comment by DzzD** [comment]
> This problems already fixed in go2rtc project. The changes will get into this project along with replacing rtsp2webrtc with go2rtc.
> 
> You also created a Discussion in the go2rtc project, but you attached screenshots of rtsp2webrtc. This is wrong. These are different projects.

Ho sorry, this is probably because I am mixing between projects, but I have an instance(container) of go2trtc running and I have set its listening IP:port of this integration of RTSPToWebRTC, but in fact if I stop the go2rtc container the problem is still their... and the camera works as usual, and if I kill the process "rtsp2webrtc_v5_" it stop camera for few secondes and it reappear few seconds later, I am lost in what "go2rtc" and "RTSPToWebRTC" are for ? it seems that WebRTC (custom:webrtc-camera) can work alone very well ? 

![image](https://user-images.githubusercontent.com/12198339/209950967-69de11f7-a32d-4d91-8e73-03f59881b664.png)

**Comment by AlexxIT** [comment]
You can find answers on your questions in go2rtc docs. FAQ section.
