### ISSUE TITLE
Stream not working with Version 2.0

### ISSUE THREAD

**Issue by weitheng** [AlexxIT/WebRTC#49]
Getting error message on new version. Tried on Safari Desktop and HA iOS App
![Screenshot 2021-05-04 at 06 05 50](https://user-images.githubusercontent.com/34220268/116962778-e4e5ae80-ac9e-11eb-9d7f-f9fd30e15057.png)

**Comment by Se7enair** [comment]
Same problem here.

card:
`type: 'custom:webrtc-camera'
url: '!secret garten_kamera_hof_stream'
`
core: 2021.4.5
su: 2021.04.3
HomeAssistant OS: 5.12
Browser: Firefox 88.0

Same on iPhone 7 wit iOS 14.5

Changed nothing, except the update. Updated from 1.3 to 1.4 to 2.0 without restart between 1.4 and 2.0. Did a restart after 2.0

**Comment by LEJOUI** [comment]
In the logs I've this error
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:87
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:09:09 (2 occurrences)
Last logged: 9:09:09

[140175567879424] Received invalid command: webrtc/stream
```

**Comment by inah72** [comment]
reload page many times then works with chrome

**Comment by LEJOUI** [comment]
> reload page many times then works with chrome or empty cache

Thanks. Cache deleted fixed it.

**Comment by weitheng** [comment]
Now seems to work fine, changed nothing on HA iOS App, but cleared cache and website data on Safari Web

**Comment by AlexxIT** [comment]
The cache problem is fixed in the latest master version.

@shammysha How do you set a password for your camera? In the lovelace card or in the camera entity?

**Comment by Se7enair** [comment]
BigBuckBunny Stream is playing after clearing the cache.
My camera now shows
`ERROR: Support only RTSP-Stream`

**Comment by AlexxIT** [comment]
RTSP check is very simple, url must starts with rtsp

**Comment by shammysha** [comment]
> The cache problem is fixed in the latest master version.
> 
> @shammysha How do you set a password for your camera? In the lovelace card or in the camera entity?

I do not set passwd for camera anywhere

**Comment by AlexxIT** [comment]
@shammysha so you need to do it, because your camera doesn't work without it

**Comment by Se7enair** [comment]
> RTSP check is very simple, url must starts with `rtsp`

The url is a rtsp-stream. But I use a secret there. If I change to the direct url it works.

So using a secret is not possible at the moment.

```
type: 'custom:webrtc-camera'
url: '!secret garten_kamera_hof_stream'
```

**Comment by shammysha** [comment]
> @shammysha so you need to do it, because your camera doesn't work without it

In rtsp url to camera password exist.

**Comment by weitheng** [comment]
> The cache problem is fixed in the latest master version.
> 
> @shammysha How do you set a password for your camera? In the lovelace card or in the camera entity?

Updated to the master version. Stream seems to take more than 2-5 seconds to load on my HA iOS App running on iOS 14.6, iPhone 11. Previously stream loads instantly. Is this normal?

**Comment by AlexxIT** [comment]
@Se7enair you can't use secret in lovelace card. Create ffmpeg or generic camera and use it entity in webrtc card config

**Comment by AlexxIT** [comment]
@shammysha what chars in your pass? Letters/numb or some spec?

**Comment by AlexxIT** [comment]
@shammysha fix in latest master version

**Comment by majkers** [comment]
@AlexxIT how about new official version? :)

**Comment by AlexxIT** [comment]
Need to collect more hotfixes

**Comment by AlexxIT** [comment]
@weitheng iOS doesn't support MSE, I have fixed readme.

WebRTC not always starts instantly. Sometimes it takes time to get a public IP address. In theory, the connection can be speeded up, but there is a lot of work need to be done.

**Comment by Se7enair** [comment]
> @Se7enair you can't use secret in lovelace card. Create ffmpeg or generic camera and use it entity in webrtc card config

I tested only on a testcard directly in lovelace. There it wont work.

Normally I use the card as a popup on my dashboard, there it works with secret.

```
              action: fire-dom-event
              browser_mod:
                command: popup
                title: Hof
                style:
                  .: |
                    :host .content {
                      width: 1280px;
                    }
                card:
                  type: 'custom:webrtc-camera'
                  url: !secret garten_kamera_hof_stream
```

**Comment by Gferretta** [comment]
Do not function for me. 😪
Last version show this errors
![Screenshot_20210504-085324_Home Assistant.jpg](https://user-images.githubusercontent.com/65413059/117002021-6a765800-acb9-11eb-9464-1f48c6f53ee6.jpg)

**Comment by shammysha** [comment]
> @shammysha fix in latest master version

Reinstall via HACS, error {"error":"RTSP Client Unauthorized 401"} still exists

**Comment by majkers** [comment]
> > @shammysha fix in latest master version
> 
> Reinstall via HACS, error {"error":"RTSP Client Unauthorized 401"} still exists

master is not the same as HACS version...at least for now

**Comment by weitheng** [comment]
> @weitheng iOS doesn't support MSE, I have fixed readme.
> 
> WebRTC not always starts instantly. Sometimes it takes time to get a public IP address. In theory, the connection can be speeded up, but there is a lot of work need to be done.

I see. But before updating to Version 2.0.0, it was way faster, no long delay before the stream was played. Could it be because MSE is listed as the first protocol to use first, but since it's not supported on iOS, iOS takes time to switch to get an error message from using MSE then only switch to using WebRTC?

**Comment by shammysha** [comment]
> > > @shammysha fix in latest master version
> > 
> > 
> > Reinstall via HACS, error {"error":"RTSP Client Unauthorized 401"} still exists
> 
> master is not the same as HACS version...at least for now

Thank You. Will test when HACs version become the same as master :)

**Comment by weitheng** [comment]
> > @weitheng iOS doesn't support MSE, I have fixed readme.
> > WebRTC not always starts instantly. Sometimes it takes time to get a public IP address. In theory, the connection can be speeded up, but there is a lot of work need to be done.
> 
> I see. But before updating to Version 2.0.0, it was way faster, no long delay before the stream was played. Because right now, it is consistently taking 10-15 seconds before the streams starts playing. I have tried multiple times and over different networks (WiFi, Mobile Data)
> 
> Is it normal to be getting this message every time before a stream starts? `2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] 2021/05/04 21:45:28 websocket.JSON.Receive EOF`

Getting this:
```
2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] 2021/05/04 21:45:28 websocket.JSON.Receive EOF
2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2021/05/04 - 21:45:28 | 200 | 1.75648582s | 127.0.0.1 | GET "/ws?url=rtsp://admin:XXXX@192.168.0.XX:554/cam/realmonitor?channel%3D1%26subtype%3D0%26unicast%3Dtrue%26proto%3DOnvif"
2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] 2021/05/04 21:45:28 websocket.JSON.Receive EOF
2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2021/05/04 - 21:45:28 | 200 | 1.756810889s | 127.0.0.1 | GET "/ws?url=rtsp://admin:XXXX@192.168.0.XX:554/cam/realmonitor?channel%3D12%26subtype%3D0"
```

**Comment by shammysha** [comment]
Alphanumeric symbols only

**Comment by weitheng** [comment]
> > > @weitheng iOS doesn't support MSE, I have fixed readme.
> > > WebRTC not always starts instantly. Sometimes it takes time to get a public IP address. In theory, the connection can be speeded up, but there is a lot of work need to be done.
> > 
> > 
> > I see. But before updating to Version 2.0.0, it was way faster, no long delay before the stream was played. Because right now, it is consistently taking 10-15 seconds before the streams starts playing. I have tried multiple times and over different networks (WiFi, Mobile Data)
> > Is it normal to be getting this message every time before a stream starts? `2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] 2021/05/04 21:45:28 websocket.JSON.Receive EOF`
> 
> Getting this while playing on iOS HA App:
> 
> ```
> 2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] 2021/05/04 21:45:28 websocket.JSON.Receive EOF
> 2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2021/05/04 - 21:45:28 | 200 | 11.75648582s | 127.0.0.1 | GET "/ws?url=rtsp://admin:XXXX@192.168.0.XX:554/cam/realmonitor?channel%3D1%26subtype%3D0%26unicast%3Dtrue%26proto%3DOnvif"
> 2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] 2021/05/04 21:45:28 websocket.JSON.Receive EOF
> 2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2021/05/04 - 21:45:28 | 200 | 11.756810889s | 127.0.0.1 | GET "/ws?url=rtsp://admin:XXXX@192.168.0.XX:554/cam/realmonitor?channel%3D12%26subtype%3D0"
> ```

Had a looked at the code and noticed the difference in using web sockets (`ws`) over stream in Version 2.0.0. Previously video stream takes milliseconds to load
`2021-05-04 21:51:27 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2021/04/22 - 13:51:27 | 200 |  147.851143ms |       127.0.0.1 | POST     "/stream"` but in Version 2.0.0, using `ws`, video streams take seconds to load
`2021-05-04 21:45:28 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2021/05/04 - 21:45:28 | 200 | 11.75648582s | 127.0.0.1 | GET "/ws?url=rtsp://admin:XXXX@192.168.0.XX:554/cam/realmonitor?channel%3D1%26subtype%3D0%26unicast%3Dtrue%26proto%3DOnvif"`

**Comment by shammysha** [comment]
> > @shammysha fix in latest master version
> 
> Reinstall via HACS, error {"error":"RTSP Client Unauthorized 401"} still exists

Changed url to format rtsp://admin:password@address:port
Now all work correct

**Comment by Gferretta** [comment]
> > > @shammysha fix in latest master version
> > 
> > Reinstall via HACS, error {"error":"RTSP Client Unauthorized 401"} still exists
> 
> Changed url to format rtsp://admin:password@address:port
> Now all work correct
> 

I has setting in this form and not working.

**Comment by majkers** [comment]
ok testing v2.0.1 with two cameras. I have it working for the first but the second is not with error:

`webrtc-camera.js?v2.0.1:72 DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.
    at WebSocket.ws.onmessage (http://ha:8123/webrtc/webrtc-camera.js?v2.0.1:70:34)`

**Comment by AlexxIT** [comment]
`/api/hls/...` - this is not from my component

`Failed to execute 'appendBuffer'` and loading circle it normal situation with some "slow" cameras or connection.

Maybe you just have a problem with the Internet?

**Comment by majkers** [comment]
But these errors heppen when stream is in connection phase. After connected they stop. No I have no problems with connection to the internet

**Comment by weitheng** [comment]
> > The cache problem is fixed in the latest master version.
> > @shammysha How do you set a password for your camera? In the lovelace card or in the camera entity?
> 
> Updated to the master version. Stream seems to take more than 10-15 seconds to load (blank screen) on my HA iOS App running on iOS 14.6, iPhone 11; iPadOS 14.4.1, iPad mini 4. Previously stream loads instantly. Is this normal?
> 
> On Safari Desktop, there's almost no delay. I suspect it is due to the CPU usage as it defaults to MSE at the start or because iOS 14.6 doesn't play over MSE, as once WebRTC takes over (delay of few seconds), it plays smoothly and instantly?

The delay is fixed with the latest master version. Thanks @AlexxIT :)

**Comment by AlexxIT** [comment]
I think problems in this issue closed in latest version
